#include <stdint.h>

#define LEA_128_RNDS           24
#define LEA_128_KEY_LEN        16

#define LEA_192_RNDS           28
#define LEA_192_KEY_LEN        24

#define LEA_256_RNDS           32
#define LEA_256_KEY_LEN        32

#define LEA_MAX_RNDS           32
#define LEA_MAX_KEY_LEN        32
#define LEA_BLOCK_LEN          16
#define LEA_RNDKEY_WORD_LEN     6   

#define ROR(W,i)    (((uint32_t)(W)>>(int)(i)) | ((uint32_t)(W)<<(32-(int)(i))))
#define ROL(W,i)    (((uint32_t)(W)<<(int)(i)) | ((uint32_t)(W)>>(32-(int)(i))))
#define BTOW(x)     (((uint32_t)(x)[3] << 24) ^ ((uint32_t)(x)[2] << 16) ^ ((uint32_t)(x)[1] <<  8) ^ ((uint32_t)(x)[0]))
#define WTOB(x, v)  { (x)[3] = (unsigned char)((v) >> 24); (x)[2] = (unsigned char)((v) >> 16); (x)[1] = (unsigned char)((v) >>  8); (x)[0] = (unsigned char)(v); }

#define msb ((uint_least32_t) 0x80000000)
#define lsb ((uint_least32_t) 0x00000001)
#define MASK_WL ((uint_least32_t)0xFFFFFFFF)

typedef struct
{
	unsigned char mk[LEA_MAX_KEY_LEN];
	unsigned char p[160];
	unsigned char c[160];
} LEA_MMT_ECB;

typedef struct
{
	unsigned char mk[LEA_MAX_KEY_LEN];
	unsigned char iv[LEA_BLOCK_LEN];
	unsigned char p[160];
	unsigned char c[160];
} LEA_MMT_CBC, LEA_MMT_CTR;


/**
 * @brief Genertate round keys by using "MasterKey"
 * 
 * @param RndKeys Round key 
 * @param MasterKey Master key for generate round keys
 * @param KeyBytes Length of master key. 
 * @return This function returns number of rounds(24, 28, 32). If there is an error, return appropriate error number
 */
int LEA_Key_Schedule(uint32_t RndKeys[LEA_MAX_RNDS][LEA_RNDKEY_WORD_LEN],
					 const unsigned char MasterKey[LEA_MAX_KEY_LEN], const int KeyBytes);

/**
 * @brief LEA encryption primitive
 * 
 * @param ct Cipher text 
 * @param pt Plain text to be encrypted
 * @param RndKeys Round keys that generated by LEA_Key_Schedule
 * @param Nr Number of rounds. It is return value of LEA_Key_Schedule
 */
void LEA_Encryption(unsigned char ct[LEA_BLOCK_LEN], const unsigned char pt[LEA_BLOCK_LEN],
					uint32_t RndKeys[LEA_MAX_RNDS][LEA_RNDKEY_WORD_LEN], const int Nr);

/**
 * @brief LEA decryption primitive
 * 
 * @param pt Plain text 
 * @param ct Cipher text to be decrypted
 * @param RndKeys Round keys that generated by LEA_Key_Schedule
 * @param Nr Number of rounds. It is return value of LEA_Key_Schedule
 */
void LEA_Decryption(unsigned char pt[LEA_BLOCK_LEN], const unsigned char ct[LEA_BLOCK_LEN],
					uint32_t RndKeys[LEA_MAX_RNDS][LEA_RNDKEY_WORD_LEN], const int Nr);	

/**
 * @brief LEA encryption process using ECB mode
 * 
 * @param ct Cipher text
 * @param pt Plain text to be encrypted using ECB mode
 * @param MasterKey Master key to generate round keys
 * @param pt_size Size of plain text in bytes
 * @param KeyBytes Length of master key
 */
void ECB_LEA_Enc(unsigned char *ct, const unsigned char *pt,
				 const unsigned char MasterKey[LEA_MAX_KEY_LEN], const int pt_size, const int KeyBytes);

/**
 * @brief LEA decryption process using ECB mode
 * 
 * @param pt Plain text
 * @param ct Cipher text to be decrypted using ECB mode
 * @param MasterKey Master key to generate round keys
 * @param ct_size Size of cipher text in bytes
 * @param KeyBytes Length of master key
 */
void ECB_LEA_Dec(unsigned char *pt, const unsigned char *ct,
				 const unsigned char MasterKey[LEA_MAX_KEY_LEN], const int ct_size, const int KeyBytes);

/**
 * @brief LEA encryption process using CBC mode
 * 
 * @param ct Cipher text
 * @param pt Plain text to be encrypted using CBC mode
 * @param MasterKey Master key to generate round keys
 * @param IV Initialize vector 
 * @param pt_size Size of plain text in bytes
 * @param KeyBytes Length of master key
 */
void CBC_LEA_Enc(unsigned char *ct, const unsigned char *pt, const unsigned char MasterKey[LEA_MAX_KEY_LEN], 
				 const unsigned char IV[LEA_BLOCK_LEN], const int pt_size, const int KeyBytes);

/**
 * @brief LEA decryption process using CBC mode
 * 
 * @param pt Plain text
 * @param ct Cipher text to be decrypted using CBC mode
 * @param MasterKey Master key to generate round keys
 * @param IV Initialize vector
 * @param ct_size Size of cipher text in bytes
 * @param KeyBytes Length of master key
 */
void CBC_LEA_Dec(unsigned char *pt, const unsigned char *ct, const unsigned char MasterKey[LEA_MAX_KEY_LEN],
				 const unsigned char IV[LEA_BLOCK_LEN], const int ct_size, const int KeyBytes);

/**
 * @brief LEA encryption process using CTR mode
 * 
 * @param ct Cipher text
 * @param pt Plain text to be encrypted using CTR mode
 * @param MasterKey Master key to generate round keys
 * @param IV Initialize vector
 * @param pt_size Size of cipher text in bytes
 * @param KeyBytes Length of master key
 */
void CTR_LEA_Enc(unsigned char *ct, const unsigned char *pt, const unsigned char MasterKey[LEA_MAX_KEY_LEN], 
				 const unsigned char IV[LEA_BLOCK_LEN], const int pt_size, const int KeyBytes);

/**
 * @brief LEA decryption process using CTR mode
 * 
 * @param pt Plain text
 * @param ct Cipher text to be decrypted using CTR mode
 * @param MasterKey Master key to generate round keys
 * @param IV Initialize vector
 * @param ct_size Size of cipher text in bytes
 * @param KeyBytes Length of master key
 */
void CTR_LEA_Dec(unsigned char *pt, const unsigned char *ct, const unsigned char MasterKey[LEA_MAX_KEY_LEN], 
                 const unsigned char IV[LEA_BLOCK_LEN], const int ct_size, const int KeyBytes);